### ISSUE TITLE
assign value to notebookContent 

### ISSUE THREAD

**Issue by IntranetFactory** [gzuidhof/starboard-wrap#1]
I was trying to assign a value ` el.notebookContent = "# %% [javascript]\n3+5\n";` after the notebook was already added to the DOM, but the new value is ignored.
   
Should that work?  https://github.com/apinotebooks/starboard-wrap/blob/master/examples/default-assign.html#L15

**Comment by IntranetFactory** [comment]
I found that 

```js
    el.sendMessage({
      type: "NOTEBOOK_SET_INIT_DATA", payload: {content}
    });
```

allows to assign the notebook. But I think that's not a stable solution as that doesn't check for/delay until NOTEBOOK_READY_SIGNAL

**Comment by gzuidhof** [comment]
After setting the content you can send a `NOTEBOOK_RELOAD_PAGE` message, which will make the `NOTEBOOK_READY_SIGNAL` get sent again :).

You probably want to reload the page anyhow to get rid of any existing state. Let me know if this works for you!
