### ISSUE TITLE
empty notebookContent causes cut off pixels at the end of the notebook

### ISSUE THREAD

**Issue by IntranetFactory** [gzuidhof/starboard-wrap#2]
e.g. https://github.com/apinotebooks/starboard-wrap/blob/master/examples/default-empty.html#L8 

![image](https://user-images.githubusercontent.com/7462342/112380852-2cfdd280-8cea-11eb-893e-ba668c465068.png)

**Comment by gzuidhof** [comment]
This is an issue with the `iframeResizer` library not estimating the size of the notebook correctly. You could add some padding to the embedded page to alleviate this issue, but it will be difficult to fix for every case.

**Comment by gzuidhof** [comment]
This has been resolved since 0.4.0
